server:
  port: 8090
spring:
  application:
    name: "loans"
  profiles:
    active: "default"
  datasource:
    url: jdbc:mysql://localhost:3306/msdb
    username: kotlin
    password: kotlin1234
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"

#build:
#  version: "3.0"
#
#loans:
#  message: "Welcome to EazyBank loans related local APIs "
#  contactDetails:
#    name: "Amaal Grega - Developer"
#    email: "amaal@eazybank.com"
#  onCallSupport:
#    - (452) 456-2176
#    - (546) 764-8934