spring.application.name=message
spring.profiles.active=default
server.port=9010

spring.cloud.function.definition=email|sms
# define input binding for each function accepting input data
spring.cloud.stream.bindings.emailsms-in-0.destination=send-communication
spring.cloud.stream.bindings.emailsms-in-0.group=${spring.application.name}
# define output binding for each function producing output data
spring.cloud.stream.bindings.emailsms-out-0.destination=communication-sent
spring.cloud.stream.kafka.binder.brokers=localhost:9092
